### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'atype'

### ISSUE THREAD

**Issue by chedabd** [nilmolne/Text-Mining-The-New-York-Times-Articles#2]
Hi
Thank you for you work, it's very helpful. 

But I'm receiving this error and I'm not sure what to do about it ?
`Retrieving articles URL...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-1f3c31b409eb> in <module>()
      3 
      4 # Get Article URL List
----> 5 articles_df = get_articles_url(api, country, start_year, end_year)
      6 articles_df.tail()

1 frames
/usr/local/lib/python3.6/dist-packages/textminingnyt.py in get_articles_url(api, country, start_year, end_year)
     93 
     94     # Make sure we filter out non-news articles and remove 'atype' column
---> 95     articles_df = articles_df.drop(articles_df[articles_df.atype != 'News'].index)
     96     articles_df.drop('atype', axis = 1, inplace = True)
     97 

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py in __getattr__(self, name)
   5272             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5273                 return self[name]
-> 5274             return object.__getattribute__(self, name)
   5275 
   5276     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'atype'

I hope you can help me
Thanks`

**Comment by MiriaLP** [comment]
Exactly that happened to me.
Did you manage to solve this?

**Comment by chedabd** [comment]
Yes we rewrite large part of the Code, you can find an example here
`articles = nyt.article_search(
    query="Tunis,Tunisia ",
    results =2000,
    dates = {
        "begin": datetime.datetime(start_year, 1, 31),
        "end": datetime.datetime(end_year, 12, 31)
    },
    options = {
        "sort": "oldest",
        "sources": [
            "New York Times",
            "AP",
            "Reuters",
            "International Herald Tribune"
        ],
          "news_desk": [
            (news_desk)
          ]
    }
)`

You can find our project here : https://github.com/chedabd/Text-Mining-The-New-York-Times-Articles

**Comment by MiriaLP** [comment]
> Yes we rewrite large part of the Code, you can find an example here `articles = nyt.article_search( query="Tunis,Tunisia ", results =2000, dates = { "begin": datetime.datetime(start_year, 1, 31), "end": datetime.datetime(end_year, 12, 31) }, options = { "sort": "oldest", "sources": [ "New York Times", "AP", "Reuters", "International Herald Tribune" ], "news_desk": [ (news_desk) ] } )`
> 
> You can find our project here : https://github.com/chedabd/Text-Mining-The-New-York-Times-Articles

Thanks
